import re

from backend.ingestion.pii.models import ReadCacheError

# List of keywords that should not be anonymized even if detected as PII
EXCLUDE_FROM_PII_SYMBOLS = {
    # English keywords / table headers
    "date",
    "account",
    "description",
    "transaction",
    "type",
    "symbol",
    "quantity",
    "price",
    "currency",
    "gross",
    "amount",
    "commission",
    "net",
    "buy",
    "sell",
    "deposit",
    "withdrawal",
    "transfer",
    "forex",
    "trade",
    "starting",
    "cash",
    "ending",
    "change",
    "total",
    "fee",
    "fees",
    "tax",
    "taxes",
    "base",
    "component",
    "shares",
    "share",
    "order",
    "executed",
    "via",
    "for",
    "stock",
    "etf",
    "dividend",
    "salary",
    "pension",
    "payout",
    "isin",
    "to",
    "from",
    "the",
    "a",
    "an",
    "of",
    "in",
    "on",
    "by",
    "at",
    "with",
    "and",
    "or",
    "but",
    "as",
    # Italian keywords / table headers
    "data",
    "conto",
    "descrizione",
    "tipo",
    "operazione",
    "simbolo",
    "quantita",
    "prezzo",
    "valuta",
    "importo",
    "commissioni",
    "netto",
    "acquisto",
    "vendita",
    "deposito",
    "prelievo",
    "trasferimento",
    "totale",
    "debito",
    "credito",
    "eseguito",
    "inoltro",
    "negoziazione",
    "richiesta",
    "immissione",
    "controvalore",
    "ritenuta",
    "spese",
    "signor",
    "signora",
    "italia",
    "torino",
    "milano",
    "roma",
    "nota",
    "informativa",
    "ordine",
    "confermiamo",
    "scadenza",
    "intermediario",
    "mercato",
    "esecuzione",
    "borsa",
    "liquidazione",
    "consegna",
    "pagamento",
    "contanti",
    "effetti",
    "fiscali",
    "saranno",
    "disponibili",
    "menu",
    "gain",
    "capital",
    "cap",
    "di",
    "da",
    "con",
    "su",
    "per",
    "tra",
    "fra",
    "il",
    "la",
    "i",
    "gli",
    "le",
    "un",
    "una",
    "uno",
    "del",
    "della",
    "dei",
    "degli",
    "delle",
    "al",
    "alla",
    "ai",
    "agli",
    "alle",
    "nel",
    "nella",
    "nei",
    "negli",
    "nelle",
    "col",
    "coi",
    "sul",
    "sulla",
    "sui",
    "sugli",
    "sulle",
    "pel",
    "pei",
    "dal",
    "dalla",
    "dai",
    "dagli",
    "dalle",
    "vs",
    "vostro",
    "vostra",
    "vostri",
    "vostre",
}


DATE_TIME_REGEX = re.compile(r"^(?:del\s+)?\b(?:\d{1,2}[./-]\d{1,2}[./-]\d{2,4}|\d{2}:\d{2}:\d{2})\b$", re.IGNORECASE)

# Regex to match placeholders e.g. [ANONYMIZED_PRESIDIO_PERSON_1] or [ANONYMIZED_LLM_PERSON_1]
PLACEHOLDER_REGEX = re.compile(r"\[ANONYMIZED_[A-Z_]+_[A-Z_]+_\d+\]")


READ_CACHE_ERROR_FRIENDLY_MESSAGES: dict[ReadCacheError, str] = {
    "config-file-mismatch": "PII anonymization cache file could not be used due to configuration flag mismatch.",
    "cache-file-not-found": "PII anonymization cache file could not be found.",
    "invalid-cache-file": "PII anonymization cache file could not be processed due to corruption or invalid format.",
    "unknown-error": "An unexpected error occurred while reading from the PII anonymization cache.",
}
